// @ts-nocheck
/* Home Weavers — Supabase Edge Function "hw". GENERATED by tools/build-edge.js from ai-proxy.worker.js; edit that file instead.
   Address: https://<project>.supabase.co/functions/v1/hw   (turn OFF "Verify JWT" for this function:
   Stripe and ShipStation webhooks can't send a Supabase login; admin routes check the admin session themselves.)
   Secrets: Supabase → Edge Functions → Secrets. SUPABASE_URL, SUPABASE_ANON_KEY and SUPABASE_SERVICE_ROLE_KEY are provided by Supabase. */

/* =====================================================================
   Home Weavers — Cloudflare Worker (free plan is enough)
   ---------------------------------------------------------------------
   Keeps every secret key OFF your public website. Routes:

     POST /ai        Claude text for the Marketing studio   (admins only)
     POST /image     AI images via OpenAI (optional)         (admins only)
     POST /welcome   Newsletter welcome email via Brevo (optional)
     POST /snipcart  Snipcart "order.completed" webhook → saves the order (optional)
     POST /checkout/session     Stripe Checkout page for a placed order (shoppers)
     POST /stripe               Stripe webhook → marks the order paid, sends it to ShipStation
     POST /shipstation/push     Send one order to ShipStation again           (admins only)
     POST /shipstation/setup    Register the "order shipped" webhook          (admins only)
     POST /shipstation/webhook  ShipStation SHIP_NOTIFY / FULFILLMENT_SHIPPED → saves carrier + tracking number
     POST /shipstation/sync     Look an order up in ShipStation and save its tracking  (admins only)
     POST /order/cancel         Customer cancels inside the free window: refund + cancel  (order number + email)
     POST /orders/accept        Accept one order now and send it to ShipStation           (admins only)
     POST /orders/release       Accept orders whose cancellation window has passed        (scheduled job)
     POST /email/test           Send a sample order email to the signed-in admin           (admins only)
     POST /account/code         Customer sign-in: email a 6-digit code (only to emails that have ordered)
     POST /account/verify       Customer sign-in: check the code → signed 30-day session (no passwords)
     POST /account/orders       Signed-in customer's own orders (Authorization: Bearer <session>)
     GET  /          Health check (lists which features are set up — never the keys)

   "Admins only" = the request must carry the signed-in admin's Supabase
   session, and that email must be in the admins table. Anyone else gets 401.

   ----- SECRETS (Worker → Settings → Variables and Secrets) -----
   Required for /ai:
     ANTHROPIC_API_KEY          your Anthropic key (console.anthropic.com)
     SUPABASE_URL               https://xxxx.supabase.co
     SUPABASE_PUBLISHABLE_KEY   sb_publishable_… (the public key from js/config.js)
   Optional:
     ALLOWED_ORIGINS            comma list, e.g. https://rahul26hw.github.io,http://localhost:8080
     OPENAI_API_KEY             enables /image
     SUPABASE_SERVICE_ROLE_KEY  needed by /welcome and /snipcart (secret key — never put it in the website)
     BREVO_API_KEY, FROM_EMAIL, FROM_NAME   enables /welcome
     SNIPCART_SECRET_KEY        enables /snipcart (validates each webhook with Snipcart)
     CLAUDE_EFFORT              low | medium | high (default medium)
   Card payments (Stripe) — also need SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY:
     STRIPE_SECRET_KEY          sk_test_… / sk_live_… (Stripe → Developers → API keys)
     STRIPE_WEBHOOK_SECRET      whsec_… (Stripe → Developers → Webhooks → your endpoint)
   ShipStation (API v1) — also need SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY:
     SHIPSTATION_API_KEY, SHIPSTATION_API_SECRET   (ShipStation → Settings → Account → API Settings)
     SHIPSTATION_WEBHOOK_TOKEN  any long random text; it proves shipment calls come from your ShipStation webhook
   Customer emails (Resend):
     RESEND_API_KEY             re_… (resend.com → API Keys); the sending domain must be verified in Resend
     EMAIL_FROM                 optional, default "Home Weavers <orders@homeweavers.net>"
     EMAIL_REPLY_TO             optional, default the contact email from Admin › Storefront
   Full click-by-click setup: README.md → "AI worker".
   ===================================================================== */

const CLAUDE_MODEL = "claude-opus-5";
const DEFAULT_ORIGINS = ["https://rahul26hw.github.io", "http://localhost:8080"];

const handler = {
  async fetch(request, env) {
    const url = new URL(request.url);
    const origin = request.headers.get("Origin") || "";
    const cors = corsHeaders(origin, env);

    if (request.method === "OPTIONS") return new Response(null, { status: 204, headers: cors });
    if (request.method === "GET" && url.pathname === "/") return json({ ok: true, service: "home-weavers-worker", features: features(env) }, 200, cors);
    if (request.method !== "POST") return json({ error: "Use POST" }, 405, cors);

    try {
      switch (url.pathname.replace(/\/+$/, "")) {
        case "/ai": return await handleAI(request, env, cors);
        case "/image": return await handleImage(request, env, cors);
        case "/welcome": return await handleWelcome(request, env, cors);
        case "/snipcart": return await handleSnipcart(request, env);
        case "/checkout/session": return await handleCheckoutSession(request, env, cors);
        case "/stripe": return await handleStripeWebhook(request, env);
        case "/shipstation/push": return await handleShipstationPush(request, env, cors);
        case "/shipstation/setup": return await handleShipstationSetup(request, env, cors);
        case "/shipstation/webhook": return await handleShipstationWebhook(request, env);
        case "/shipstation/sync": return await handleShipstationSync(request, env, cors);
        case "/order/cancel": return await handleOrderCancel(request, env, cors);
        case "/orders/accept": return await handleOrderAccept(request, env, cors);
        case "/orders/release": return await handleOrderRelease(request, env, cors);
        case "/email/test": return await handleEmailTest(request, env, cors);
        case "/account/code": return await handleAccountCode(request, env, cors);
        case "/account/verify": return await handleAccountVerify(request, env, cors);
        case "/account/orders": return await handleAccountOrders(request, env, cors);
        default: return json({ error: "Not found" }, 404, cors);
      }
    } catch (e) {
      // Details go to the Cloudflare log. Only signed-in admins get them back; shoppers and webhooks get a plain message.
      console.error(url.pathname, e && e.stack ? e.stack : e);
      const adminRoute = ["/ai", "/image", "/shipstation/push", "/shipstation/setup", "/shipstation/sync", "/orders/accept", "/email/test"].includes(url.pathname.replace(/\/+$/, ""));
      return json({ error: adminRoute ? "Worker error: " + (e && e.message ? e.message : "unknown") : "Something went wrong. Please try again in a moment." }, 500, cors);
    }
  },
};

/* ---------------------------------------------------------------- *
 * Helpers
 * ---------------------------------------------------------------- */
function corsHeaders(origin, env) {
  const allowed = (env.ALLOWED_ORIGINS ? env.ALLOWED_ORIGINS.split(",") : DEFAULT_ORIGINS).map((s) => s.trim()).filter(Boolean);
  const h = {
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type, Authorization",
    "Access-Control-Max-Age": "86400",
    "Vary": "Origin",
  };
  if (allowed.includes(origin)) h["Access-Control-Allow-Origin"] = origin;
  return h;
}

function json(obj, status = 200, extra = {}) {
  return new Response(JSON.stringify(obj), { status, headers: { "Content-Type": "application/json", ...extra } });
}

async function readJson(request) {
  const text = await request.text();
  if (text.length > 200000) throw new Error("Request too large");
  try { return JSON.parse(text || "{}"); } catch { throw new Error("Invalid JSON"); }
}

/* Confirms the caller is a signed-in Home Weavers admin. */
async function requireAdmin(request, env) {
  if (!env.SUPABASE_URL || !env.SUPABASE_PUBLISHABLE_KEY) return "Worker is missing SUPABASE_URL or SUPABASE_PUBLISHABLE_KEY";
  const auth = request.headers.get("Authorization") || "";
  if (!/^Bearer\s+\S+/.test(auth)) return "Sign in to the admin first";
  const headers = { apikey: env.SUPABASE_PUBLISHABLE_KEY, Authorization: auth, "Content-Type": "application/json" };
  const user = await fetch(env.SUPABASE_URL + "/auth/v1/user", { headers });
  if (!user.ok) return "Your admin session expired — sign in again";
  const check = await fetch(env.SUPABASE_URL + "/rest/v1/rpc/is_admin", { method: "POST", headers, body: "{}" });
  if (!check.ok || (await check.json()) !== true) return "This account isn’t an admin";
  return null;
}

function serviceHeaders(env) {
  const key = env.SUPABASE_SERVICE_ROLE_KEY;
  const h = { apikey: key, "Content-Type": "application/json" };
  // Legacy service_role keys are JWTs and also go in Authorization; new sb_secret_ keys go in apikey only.
  if (/^eyJ/.test(String(key || ""))) h.Authorization = "Bearer " + key;
  return h;
}

/* ---------------------------------------------------------------- *
 * POST /ai  { system, prompt }  →  { text }
 * ---------------------------------------------------------------- */
async function handleAI(request, env, cors) {
  const denied = await requireAdmin(request, env);
  if (denied) return json({ error: denied }, 401, cors);
  if (!env.ANTHROPIC_API_KEY) return json({ error: "Worker is missing ANTHROPIC_API_KEY" }, 500, cors);

  const body = await readJson(request);
  const prompt = String(body.prompt || "").slice(0, 20000);
  const system = String(body.system || "").slice(0, 4000);
  if (!prompt) return json({ error: "Missing prompt" }, 400, cors);

  const effort = ["low", "medium", "high"].includes(env.CLAUDE_EFFORT) ? env.CLAUDE_EFFORT : "medium";
  const upstream = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "content-type": "application/json",
      "x-api-key": env.ANTHROPIC_API_KEY,
      "anthropic-version": "2023-06-01",
      // If Claude declines a request, retry it on Anthropic's recommended fallback model.
      "anthropic-beta": "server-side-fallback-2026-07-01",
    },
    body: JSON.stringify({
      model: CLAUDE_MODEL,
      max_tokens: 16000,
      fallbacks: "default",
      output_config: { effort },
      system: system || undefined,
      messages: [{ role: "user", content: prompt }],
    }),
  });

  let data;
  try { data = await upstream.json(); } catch { data = {}; }
  if (!upstream.ok) {
    const msg = (data && data.error && data.error.message) || ("Anthropic API error " + upstream.status);
    return json({ error: msg }, upstream.status === 401 ? 500 : upstream.status, cors);
  }
  if (data.stop_reason === "refusal") return json({ error: "The AI declined this request. Try rewording it." }, 422, cors);

  const text = (data.content || []).filter((b) => b && b.type === "text").map((b) => b.text).join("\n").trim();
  if (!text) return json({ error: data.stop_reason === "max_tokens" ? "The reply was too long — try a smaller request." : "Empty reply from the AI" }, 502, cors);
  return json({ text, stop_reason: data.stop_reason }, 200, cors);
}

/* ---------------------------------------------------------------- *
 * POST /image  { prompt, size }  →  { image: dataURL }
 * ---------------------------------------------------------------- */
async function handleImage(request, env, cors) {
  const denied = await requireAdmin(request, env);
  if (denied) return json({ error: denied }, 401, cors);
  if (!env.OPENAI_API_KEY) return json({ error: "Image generation isn’t set up (worker is missing OPENAI_API_KEY)" }, 501, cors);

  const body = await readJson(request);
  const prompt = String(body.prompt || "").slice(0, 4000);
  const size = ["1024x1024", "1536x1024", "1024x1536"].includes(body.size) ? body.size : "1024x1024";
  if (!prompt) return json({ error: "Missing prompt" }, 400, cors);

  const upstream = await fetch("https://api.openai.com/v1/images/generations", {
    method: "POST",
    headers: { "Content-Type": "application/json", Authorization: "Bearer " + env.OPENAI_API_KEY },
    body: JSON.stringify({ model: "gpt-image-1", prompt, size, n: 1 }),
  });
  const data = await upstream.json().catch(() => ({}));
  if (!upstream.ok) return json({ error: (data.error && data.error.message) || "Image API error" }, upstream.status, cors);
  const first = data.data && data.data[0];
  if (first && first.b64_json) return json({ image: "data:image/png;base64," + first.b64_json }, 200, cors);
  if (first && first.url) return json({ url: first.url }, 200, cors);
  return json({ error: "No image returned" }, 502, cors);
}

/* ---------------------------------------------------------------- *
 * POST /welcome  { email }  → sends the welcome code once, right after sign-up.
 * Only emails that subscribed in the last 10 minutes get a message, and the
 * code/offer come from your store data (never from the request).
 * ---------------------------------------------------------------- */
async function handleWelcome(request, env, cors) {
  if (!env.BREVO_API_KEY || !env.FROM_EMAIL || !env.SUPABASE_SERVICE_ROLE_KEY || !env.SUPABASE_URL) return json({ ok: false, error: "Welcome email isn’t set up" }, 501, cors);
  const body = await readJson(request);
  const email = String(body.email || "").trim().toLowerCase();
  if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) return json({ ok: false }, 400, cors);

  const since = new Date(Date.now() - 10 * 60 * 1000).toISOString();
  const q = env.SUPABASE_URL + "/rest/v1/subscribers?select=email,created_at&email=eq." + encodeURIComponent(email) + "&created_at=gte." + encodeURIComponent(since);
  const found = await fetch(q, { headers: serviceHeaders(env) }).then((r) => r.json()).catch(() => []);
  if (!Array.isArray(found) || !found.length) return json({ ok: true }, 200, cors); // quiet: nothing to send

  const store = await fetch(env.SUPABASE_URL + "/rest/v1/store?id=eq.main&select=data", { headers: serviceHeaders(env) }).then((r) => r.json()).catch(() => []);
  const data = (store[0] && store[0].data) || {};
  const brand = (data.brand && data.brand.name) || "Home Weavers";
  const code = String((data.newsletter && data.newsletter.couponCode) || "");
  const promo = (data.promos || []).find((p) => p.active && String(p.code).toUpperCase() === code.toUpperCase());
  const offer = promo ? (promo.type === "percent" ? promo.value + "% off" : "$" + promo.value + " off") : "";
  const site = (data.settings && data.settings.siteUrl) || "";

  const html = `<div style="font-family:Arial,sans-serif;color:#2A2622;max-width:520px;margin:auto;padding:24px">
    <h1 style="font-family:Georgia,serif;font-weight:400">Welcome to ${esc(brand)}</h1>
    <p>Thanks for joining our list. You’ll be first to see new arrivals.</p>
    ${promo ? `<p>Here’s <b>${esc(offer)}</b> your first order:</p><p style="font-size:22px;letter-spacing:2px;background:#EFEAE1;padding:12px 16px;display:inline-block"><b>${esc(promo.code)}</b></p>` : ""}
    ${site ? `<p><a href="${esc(site)}" style="color:#3A5A52">Shop now</a></p>` : ""}
    <p style="color:#6C6359;font-size:12px">You received this because you signed up at ${esc(brand)}.</p></div>`;

  const sent = await fetch("https://api.brevo.com/v3/smtp/email", {
    method: "POST",
    headers: { "api-key": env.BREVO_API_KEY, "Content-Type": "application/json", accept: "application/json" },
    body: JSON.stringify({
      sender: { email: env.FROM_EMAIL, name: env.FROM_NAME || brand },
      to: [{ email }],
      subject: promo ? `Your ${offer} code from ${brand}` : `Welcome to ${brand}`,
      htmlContent: html,
    }),
  });
  return json({ ok: sent.ok }, sent.ok ? 200 : 502, cors);
}

function esc(s) {
  return String(s == null ? "" : s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
}

/* ---------------------------------------------------------------- *
 * POST /snipcart — Snipcart webhook (Snipcart dashboard → Account → Webhooks).
 * Every call is checked with Snipcart before anything is saved.
 * ---------------------------------------------------------------- */
async function handleSnipcart(request, env) {
  if (!env.SNIPCART_SECRET_KEY || !env.SUPABASE_SERVICE_ROLE_KEY || !env.SUPABASE_URL) return json({ error: "Snipcart webhook isn’t set up" }, 501);
  const token = request.headers.get("X-Snipcart-RequestToken");
  if (!token) return json({ error: "Missing request token" }, 401);
  const check = await fetch("https://app.snipcart.com/api/requestvalidation/" + encodeURIComponent(token), {
    headers: { Accept: "application/json", Authorization: "Basic " + btoa(env.SNIPCART_SECRET_KEY + ":") },
  });
  if (!check.ok) return json({ error: "Request could not be validated with Snipcart" }, 401);

  const body = await readJson(request);
  if (body.eventName !== "order.completed") return json({ ok: true, ignored: body.eventName || "unknown" });
  const o = body.content || {};
  const ship = o.shippingAddress || o.billingAddress || {};
  const number = "SC-" + String(o.invoiceNumber || o.token || Date.now()).replace(/[^A-Za-z0-9-]/g, "").slice(0, 30);

  const order = {
    order_number: number,
    email: String(o.email || "").toLowerCase(),
    name: ship.fullName || ship.name || (o.user && o.user.billingAddressName) || "Snipcart customer",
    phone: ship.phone || null,
    shipping_address: {
      line1: ship.address1 || "", line2: ship.address2 || "", city: ship.city || "",
      state: ship.province || "", zip: ship.postalCode || "", country: ship.country || "",
    },
    subtotal: Number(o.subtotal || o.itemsTotal || 0),
    discount: Number(o.discountsTotal || o.rebateAmount || 0),
    shipping: Number(o.shippingFees || 0),
    tax: Number(o.taxesTotal || o.totalTaxes || 0),
    total: Number(o.grandTotal || o.finalGrandTotal || o.total || 0),
    currency: String(o.currency || "usd").toLowerCase(),
    promo_code: (o.discounts && o.discounts[0] && o.discounts[0].code) || null,
    status: "new",
    payment_status: "paid",
    source: "snipcart",
    external_id: String(o.token || number),
  };

  const ins = await fetch(env.SUPABASE_URL + "/rest/v1/orders?on_conflict=external_id", {
    method: "POST",
    headers: { ...serviceHeaders(env), Prefer: "return=representation,resolution=ignore-duplicates" },
    body: JSON.stringify(order),
  });
  const rows = await ins.json().catch(() => []);
  if (!ins.ok) return json({ error: "Could not save order", detail: rows }, 500);
  if (!Array.isArray(rows) || !rows.length) return json({ ok: true, duplicate: true });

  const items = (o.items || []).map((i) => ({
    order_id: rows[0].id,
    product_id: null,
    sku: String(i.id || ""),
    name: String(i.name || "Item"),
    variant: (i.customFields || []).map((f) => f.value).filter(Boolean).join(" / ") || null,
    unit_price: Number(i.price || 0),
    qty: Math.max(1, Number(i.quantity || 1)),
    line_total: Number(i.totalPrice || (Number(i.price || 0) * Number(i.quantity || 1))),
    image: i.image || null,
  }));
  if (items.length) {
    await fetch(env.SUPABASE_URL + "/rest/v1/order_items", { method: "POST", headers: { ...serviceHeaders(env), Prefer: "return=minimal" }, body: JSON.stringify(items) });
  }
  return json({ ok: true, order: number });
}

/* ================================================================ *
 * Payments (Stripe Checkout) and shipping (ShipStation API v1)
 * ================================================================ */
function features(env) {
  const db = !!(env.SUPABASE_URL && env.SUPABASE_SERVICE_ROLE_KEY);
  const ss = !!(db && env.SHIPSTATION_API_KEY && env.SHIPSTATION_API_SECRET);
  return {
    database: db,
    email: !!env.RESEND_API_KEY,
    ai: !!(env.ANTHROPIC_API_KEY && env.SUPABASE_URL && env.SUPABASE_PUBLISHABLE_KEY),
    stripe: !!(db && env.STRIPE_SECRET_KEY && env.STRIPE_WEBHOOK_SECRET),
    stripeMode: env.STRIPE_SECRET_KEY ? (/^(sk|rk)_live_/.test(env.STRIPE_SECRET_KEY) ? "live" : "test") : null,
    shipstation: ss,
    shipstationWebhook: !!(ss && env.SHIPSTATION_WEBHOOK_TOKEN),
  };
}

const cents = (n) => Math.round(Number(n || 0) * 100);
const UUID = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/* Compares secrets without leaking timing. */
function safeEqual(a, b) {
  a = String(a); b = String(b);
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

async function db(env, path, init = {}) {
  const res = await fetch(env.SUPABASE_URL + "/rest/v1/" + path, { ...init, headers: { ...serviceHeaders(env), ...(init.headers || {}) } });
  const text = await res.text();
  let data = null;
  try { data = text ? JSON.parse(text) : null; } catch { data = text; }
  if (!res.ok) throw new Error("Database error " + res.status + ": " + String((data && data.message) || text).slice(0, 200));
  return data;
}

async function loadOrder(env, filter) {
  const rows = await db(env, "orders?" + filter + "&select=*,order_items(*)&limit=1");
  return Array.isArray(rows) && rows[0] ? rows[0] : null;
}

async function patchOrder(env, filter, patch) {
  return db(env, "orders?" + filter, { method: "PATCH", headers: { Prefer: "return=representation" }, body: JSON.stringify(patch) });
}

/* Minutes a customer can cancel a paid order themselves (Admin › Storefront, default 30). */
async function cancelMinutes(env) {
  const rows = await db(env, "store?id=eq.main&select=data");
  const n = Number(((rows && rows[0] && rows[0].data && rows[0].data.settings) || {}).cancelMinutes);
  return n >= 0 && n <= 1440 ? n : 30;
}

/* ---------------------------------------------------------------- *
 * POST /order/cancel  { order_number, email }  → refunds and cancels inside the free window
 * ---------------------------------------------------------------- */
async function handleOrderCancel(request, env, cors) {
  if (!features(env).database) return json({ error: "Orders aren’t set up yet." }, 501, cors);
  const body = await readJson(request);
  const number = String(body.order_number || "").trim().toUpperCase();
  const email = String(body.email || "").trim().toLowerCase();
  if (!/^[A-Z]{2,4}-\d{1,12}$/.test(number) || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)) return json({ error: "Order not found" }, 404, cors);

  const order = await loadOrder(env, "order_number=eq." + encodeURIComponent(number) + "&email=eq." + encodeURIComponent(email));
  if (!order) return json({ error: "Order not found" }, 404, cors);
  if (order.status === "cancelled") return json({ ok: true, already: true }, 200, cors);

  const minutes = await cancelMinutes(env);
  const started = new Date(order.paid_at || order.created_at).getTime();
  const left = started + minutes * 60000 - Date.now();
  if (order.status !== "new" || left <= 0) {
    return json({ error: "This order can no longer be cancelled here.", tooLate: true, status: order.status }, 409, cors);
  }

  // Money first: if Stripe fails, the order stays as it was.
  let refunded = false, voided = false;
  if (/^pi_/.test(order.payment_ref || "") && (order.payment_status === "authorized" || order.payment_status === "paid")) {
    if (!env.STRIPE_SECRET_KEY) return json({ error: "Card payments aren’t set up. Please contact us." }, 501, cors);
    if (order.payment_status === "authorized") {
      // Nothing was charged yet: releasing the hold costs no Stripe fee.
      await stripe(env, "payment_intents/" + encodeURIComponent(order.payment_ref) + "/cancel", { cancellation_reason: "requested_by_customer" }, "void-" + order.id);
      voided = true;
    } else {
      await stripe(env, "refunds", { payment_intent: order.payment_ref, reason: "requested_by_customer" }, "refund-" + order.id);
      refunded = true;
    }
  }
  const rows = await patchOrder(env, "id=eq." + order.id + "&status=eq.new", {
    status: "cancelled",
    cancelled_at: new Date().toISOString(),
    payment_status: voided ? "voided" : refunded ? "refunded" : order.payment_status,
    cancel_reason: String(body.reason || "").slice(0, 500) || null,
  });
  if (!Array.isArray(rows) || !rows.length) return json({ error: "This order can no longer be cancelled here.", tooLate: true }, 409, cors);
  await db(env, "promo_redemptions?order_id=eq." + order.id, { method: "DELETE" }).catch(() => {});
  if (order.shipstation_order_id && features(env).shipstation) await pushToShipstation(env, { ...order, status: "cancelled" }).catch(() => {});
  await sendOrderEmail(env, "cancelled", Object.assign({}, order, rows[0]), { refunded, voided });
  return json({ ok: true, refunded, voided }, 200, cors);
}

/* Charges a held card (if any), moves the order to "accepted" and sends it to ShipStation. */
async function acceptOrder(env, order) {
  const patch = { status: "accepted", accepted_at: new Date().toISOString() };
  if (order.payment_status === "authorized") {
    try {
      const pi = await stripe(env, "payment_intents/" + encodeURIComponent(order.payment_ref) + "/capture", {}, "capture-" + order.id);
      if (pi.status !== "succeeded") throw new Error("payment is " + pi.status);
      patch.payment_status = "paid";
    } catch (e) {
      // The hold couldn't be charged (expired, card closed…): keep the order out of ShipStation.
      await patchOrder(env, "id=eq." + order.id + "&status=eq.new", {
        payment_status: "failed",
        admin_note: (order.admin_note ? order.admin_note + "\n" : "") + "⚠ Charging the card failed: " + String(e.message).slice(0, 200),
      }).catch(() => {});
      return { ok: false, order_number: order.order_number, error: "Charging the card failed: " + e.message };
    }
  }
  const rows = await patchOrder(env, "id=eq." + order.id + "&status=eq.new", patch);
  if (!Array.isArray(rows) || !rows.length) return { ok: false, skipped: order.order_number };
  const fresh = Object.assign({}, order, rows[0]);
  let shipstation = null;
  if (features(env).shipstation && !fresh.shipstation_order_id) {
    try { shipstation = (await pushToShipstation(env, fresh)).shipstation_order_id; } catch (e) { shipstation = "error: " + e.message; }
  }
  await sendOrderEmail(env, "accepted", fresh);
  return { ok: true, order_number: fresh.order_number, shipstation };
}

/* POST /orders/accept { order_id } — admins only. Accepts now, even if the window hasn't passed. */
async function handleOrderAccept(request, env, cors) {
  const denied = await requireAdmin(request, env);
  if (denied) return json({ error: denied }, 401, cors);
  const body = await readJson(request);
  if (!UUID.test(body.order_id || "")) return json({ error: "Missing order" }, 400, cors);
  const order = await loadOrder(env, "id=eq." + body.order_id);
  if (!order) return json({ error: "Order not found" }, 404, cors);
  if (order.status !== "new") return json({ error: "This order was already accepted." }, 409, cors);
  if (!/^(authorized|paid)$/.test(order.payment_status)) return json({ error: "This order isn’t paid, so it can’t be accepted." }, 409, cors);
  const r = await acceptOrder(env, order);
  return json(r, r.error ? 402 : 200, cors);
}

/* POST /orders/release — the scheduled job (and admins). Accepts every paid order whose window has passed. */
async function handleOrderRelease(request, env, cors) {
  if (!features(env).database) return json({ error: "Not set up" }, 501);
  // The scheduled job calls this without a key: it can only accept orders whose cancellation window has
  // already passed (what would happen anyway) and gets back a bare count. Admins get the details.
  const auth = (request.headers.get("Authorization") || "").replace(/^Bearer\s+/i, "");
  let trusted = !!auth && safeEqual(auth, env.SUPABASE_SERVICE_ROLE_KEY || "");
  if (!trusted && auth) trusted = !(await requireAdmin(request, env));
  const minutes = await cancelMinutes(env);
  const cutoff = new Date(Date.now() - minutes * 60000).toISOString();
  const due = await db(env, "orders?status=eq.new&payment_status=in.(authorized,paid)&paid_at=lt." + encodeURIComponent(cutoff) + "&select=*,order_items(*)&order=paid_at.asc&limit=50");
  const results = [];
  for (const order of Array.isArray(due) ? due : []) results.push(await acceptOrder(env, order));
  const accepted = results.filter((r) => r.ok).length;
  return json(trusted ? { ok: true, accepted, results } : { ok: true, accepted }, 200, cors);
}

async function siteUrl(env) {
  const rows = await db(env, "store?id=eq.main&select=data");
  const s = String((rows && rows[0] && rows[0].data && rows[0].data.settings && rows[0].data.settings.siteUrl) || "").trim();
  if (!/^https:\/\//.test(s)) throw new Error("Set “Live site address” in Admin › Storefront first");
  return s.replace(/\/?$/, "/");
}

/* Stripe takes form encoding: a[b][0][c]=1 */
function formEncode(obj, prefix, out = []) {
  for (const [k, v] of Object.entries(obj)) {
    if (v === undefined || v === null) continue;
    const key = prefix ? `${prefix}[${k}]` : k;
    if (typeof v === "object") formEncode(v, key, out);
    else out.push(encodeURIComponent(key) + "=" + encodeURIComponent(String(v)));
  }
  return out.join("&");
}

async function stripeGet(env, path) {
  const res = await fetch("https://api.stripe.com/v1/" + path, { headers: { Authorization: "Bearer " + env.STRIPE_SECRET_KEY } });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error((data.error && data.error.message) || "Stripe error " + res.status);
  return data;
}

async function stripe(env, path, params, idempotencyKey) {
  const headers = { Authorization: "Bearer " + env.STRIPE_SECRET_KEY, "Content-Type": "application/x-www-form-urlencoded" };
  if (idempotencyKey) headers["Idempotency-Key"] = idempotencyKey;
  const res = await fetch("https://api.stripe.com/v1/" + path, { method: "POST", headers, body: formEncode(params) });
  const data = await res.json().catch(() => ({}));
  if (!res.ok) throw new Error((data.error && data.error.message) || "Stripe error " + res.status);
  return data;
}

/* ---------------------------------------------------------------- *
 * POST /checkout/session  { order_number, pay_token }  →  { url }
 * Amounts come from the saved order (already priced by place_order), never from the request.
 * ---------------------------------------------------------------- */
async function handleCheckoutSession(request, env, cors) {
  if (!features(env).stripe) return json({ error: "Card payments aren’t set up yet." }, 501, cors);
  const body = await readJson(request);
  const number = String(body.order_number || "").trim().toUpperCase();
  const token = String(body.pay_token || "").trim();
  if (!/^[A-Z]{2,4}-\d{1,12}$/.test(number) || !UUID.test(token)) return json({ error: "Order not found" }, 404, cors);

  const order = await loadOrder(env, "order_number=eq." + encodeURIComponent(number));
  if (!order || !safeEqual(order.pay_token, token)) return json({ error: "Order not found" }, 404, cors);
  if (order.payment_status === "paid" || order.payment_status === "authorized") return json({ error: "This order is already paid.", paid: true }, 409, cors);
  if (order.status !== "new" || order.payment_status !== "unpaid") return json({ error: "This order can’t be paid online. Please contact us." }, 409, cors);
  if (Date.now() - new Date(order.created_at).getTime() > 7 * 24 * 3600 * 1000) return json({ error: "This order is too old to pay online. Please place it again." }, 409, cors);

  const items = order.order_items || [];
  if (!items.length || items.reduce((s, i) => s + cents(i.unit_price) * i.qty, 0) !== cents(order.subtotal)) {
    return json({ error: "This order’s total doesn’t add up. Please contact us." }, 409, cors);
  }
  const site = await siteUrl(env);
  const orderPage = site + "order/" + encodeURIComponent(order.order_number);
  const currency = order.currency || "usd";

  const params = {
    mode: "payment",
    // Cards only; Apple Pay and Google Pay appear on supported devices as card wallets.
    payment_method_types: ["card"],
    customer_email: order.email,
    client_reference_id: order.order_number,
    success_url: orderPage + "?payment=success",
    cancel_url: orderPage + "?payment=cancelled",
    expires_at: Math.floor(Date.now() / 1000) + 31 * 60,
    metadata: { order_id: order.id, order_number: order.order_number },
    // Authorize now, charge when the order is accepted: a cancellation inside the free window
    // just releases the hold, so neither the customer nor the store pays anything.
    payment_intent_data: { capture_method: "manual", description: "Order " + order.order_number, metadata: { order_id: order.id, order_number: order.order_number } },
    line_items: items.map((i) => ({
      quantity: i.qty,
      price_data: {
        currency,
        unit_amount: cents(i.unit_price),
        product_data: {
          name: (String(i.name) + (i.variant ? " — " + i.variant : "")).slice(0, 250),
          images: /^https:\/\//.test(i.image || "") ? [i.image] : undefined,
          metadata: { sku: i.sku || "" },
        },
      },
    })),
    shipping_options: [{
      shipping_rate_data: {
        type: "fixed_amount",
        display_name: cents(order.shipping) ? "Standard shipping" : "Free shipping",
        fixed_amount: { amount: cents(order.shipping), currency },
      },
    }],
  };
  if (cents(order.discount) > 0) {
    // A one-use coupon for exactly the discount place_order worked out.
    const coupon = await stripe(env, "coupons", {
      amount_off: cents(order.discount), currency, duration: "once", max_redemptions: 1,
      name: ("Discount " + (order.promo_code || "")).trim().slice(0, 40),
    }, "coupon-" + order.id);
    params.discounts = [{ coupon: coupon.id }];
  }

  const session = await stripe(env, "checkout/sessions", params);
  await patchOrder(env, "id=eq." + order.id + "&payment_status=eq.unpaid", { payment_ref: session.id });
  return json({ url: session.url }, 200, cors);
}

/* Stripe-Signature: t=…,v1=… — HMAC-SHA256 of "t.body" with the webhook secret, at most 5 minutes old. */
async function verifyStripe(env, header, payload) {
  const parts = {};
  String(header || "").split(",").forEach((p) => { const i = p.indexOf("="); if (i > 0) (parts[p.slice(0, i)] = parts[p.slice(0, i)] || []).push(p.slice(i + 1)); });
  const t = parts.t && parts.t[0];
  if (!t || !parts.v1 || !(Math.abs(Date.now() / 1000 - Number(t)) <= 300)) return false;
  const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(env.STRIPE_WEBHOOK_SECRET), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
  const sig = await crypto.subtle.sign("HMAC", key, new TextEncoder().encode(t + "." + payload));
  const hex = [...new Uint8Array(sig)].map((b) => b.toString(16).padStart(2, "0")).join("");
  return parts.v1.some((v) => safeEqual(v, hex));
}

/* ---------------------------------------------------------------- *
 * POST /stripe — Stripe webhook. Events: checkout.session.completed,
 * checkout.session.async_payment_succeeded, checkout.session.expired, charge.refunded
 * ---------------------------------------------------------------- */
async function handleStripeWebhook(request, env) {
  if (!features(env).stripe) return json({ error: "Stripe isn’t set up" }, 501);
  const payload = await request.text();
  if (!(await verifyStripe(env, request.headers.get("Stripe-Signature"), payload))) return json({ error: "Bad signature" }, 400);
  const event = JSON.parse(payload);
  const obj = (event.data && event.data.object) || {};
  const orderId = obj.metadata && obj.metadata.order_id;

  if (event.type === "checkout.session.completed" || event.type === "checkout.session.async_payment_succeeded") {
    if (!UUID.test(orderId || "")) return json({ ok: true, ignored: "no order" });
    // With authorize-only payments the session says "unpaid" while the card is held, so ask Stripe.
    const pi = obj.payment_intent ? await stripeGet(env, "payment_intents/" + encodeURIComponent(obj.payment_intent)) : null;
    const held = !!pi && pi.status === "requires_capture";
    const captured = pi ? pi.status === "succeeded" : obj.payment_status === "paid";
    if (!held && !captured) return json({ ok: true, waiting: (pi && pi.status) || obj.payment_status });
    const order = await loadOrder(env, "id=eq." + orderId);
    if (!order) return json({ ok: true, ignored: "order missing" });
    if (order.payment_status === "unpaid") {
      const amount = held ? pi.amount_capturable : obj.amount_total;
      const mismatch = amount !== cents(order.total);
      const rows = await patchOrder(env, "id=eq." + orderId + "&payment_status=eq.unpaid", {
        payment_status: held ? "authorized" : "paid",
        paid_at: new Date().toISOString(),
        payment_ref: obj.payment_intent || obj.id,
        payment_livemode: !!obj.livemode,
        status: order.status === "cancelled" ? "new" : order.status,
        admin_note: mismatch
          ? (order.admin_note ? order.admin_note + "\n" : "") + "⚠ Stripe " + (held ? "authorized" : "charged") + " $" + (amount / 100).toFixed(2) + " but the order total is $" + Number(order.total).toFixed(2) + ". Check before shipping."
          : order.admin_note,
      });
      if (Array.isArray(rows) && rows[0]) {
        Object.assign(order, rows[0]);
        await sendOrderEmail(env, "received", order);
      }
    }
    // The order now waits as "new" until it is accepted (see /orders/accept and /orders/release),
    // so the customer still has their cancellation window before anything reaches the warehouse.
    return json({ ok: true });
  }

  if (event.type === "checkout.session.expired") {
    if (!UUID.test(orderId || "")) return json({ ok: true });
    // Only the latest payment attempt cancels the order; its promo code becomes usable again.
    const rows = await patchOrder(env, "id=eq." + orderId + "&payment_status=eq.unpaid&status=eq.new&payment_ref=eq." + encodeURIComponent(obj.id), { status: "cancelled" });
    const cancelled = Array.isArray(rows) && rows.length > 0;
    if (cancelled) await db(env, "promo_redemptions?order_id=eq." + orderId, { method: "DELETE" });
    return json({ ok: true, cancelled });
  }

  if (event.type === "payment_intent.canceled" && obj.id) {
    // The card hold was released outside our cancel flow (for example it expired after 7 days).
    const rows = await patchOrder(env, "payment_ref=eq." + encodeURIComponent(obj.id) + "&payment_status=eq.authorized", { payment_status: "voided" });
    return json({ ok: true, voided: Array.isArray(rows) ? rows.length : 0 });
  }

  if (event.type === "charge.refunded" && obj.payment_intent && obj.refunded) {
    const rows = await patchOrder(env, "payment_ref=eq." + encodeURIComponent(obj.payment_intent) + "&payment_status=neq.refunded", { payment_status: "refunded" });
    if (Array.isArray(rows) && rows[0]) await sendOrderEmail(env, "refunded", rows[0], { amount: (obj.amount_refunded || 0) / 100 });
    return json({ ok: true });
  }
  return json({ ok: true, ignored: event.type });
}

/* ---------------------------------------------------------------- *
 * ShipStation (API v1)
 * ---------------------------------------------------------------- */
async function shipstation(env, path, init = {}) {
  const res = await fetch(/^https:\/\//.test(path) ? path : "https://ssapi.shipstation.com/" + path, {
    ...init,
    headers: { Authorization: "Basic " + btoa(env.SHIPSTATION_API_KEY + ":" + env.SHIPSTATION_API_SECRET), "Content-Type": "application/json", ...(init.headers || {}) },
  });
  const text = await res.text();
  let data = null;
  try { data = text ? JSON.parse(text) : null; } catch { data = text; }
  if (!res.ok) throw new Error("ShipStation " + res.status + ": " + String((data && (data.ExceptionMessage || data.Message || data.message)) || text || res.statusText).slice(0, 200));
  return data;
}

function shipstationOrder(order) {
  const a = order.shipping_address || {};
  const paid = order.payment_status === "paid";
  const items = (order.order_items || []).map((i) => ({
    lineItemKey: i.id,
    sku: i.sku || undefined,
    name: String(i.name || "Item").slice(0, 200),
    imageUrl: /^https:\/\//.test(i.image || "") ? i.image : undefined,
    quantity: i.qty,
    unitPrice: Number(i.unit_price),
    options: i.variant ? [{ name: "Option", value: i.variant }] : [],
  }));
  if (Number(order.discount) > 0) {
    items.push({ lineItemKey: "discount", name: "Discount" + (order.promo_code ? " (" + order.promo_code + ")" : ""), quantity: 1, unitPrice: -Number(order.discount), adjustment: true });
  }
  return {
    orderNumber: order.order_number,
    orderKey: order.id, // ShipStation updates the same order when this is sent again
    orderDate: order.created_at,
    paymentDate: order.paid_at || undefined,
    orderStatus: order.status === "cancelled" ? "cancelled" : paid ? "awaiting_shipment" : "awaiting_payment",
    customerUsername: order.email,
    customerEmail: order.email,
    billTo: { name: order.name },
    shipTo: {
      name: order.name, street1: a.line1 || "", street2: a.line2 || "", city: a.city || "", state: a.state || "",
      postalCode: a.zip || "", country: String(a.country || "US").slice(0, 2).toUpperCase(), phone: order.phone || "", residential: true,
    },
    items,
    amountPaid: paid ? Number(order.total) : 0,
    taxAmount: Number(order.tax || 0),
    shippingAmount: Number(order.shipping || 0),
    customerNotes: order.customer_note || undefined,
    internalNotes: order.admin_note || undefined,
    advancedOptions: { source: "Home Weavers website" },
  };
}

async function pushToShipstation(env, order) {
  try {
    const res = await shipstation(env, "orders/createorder", { method: "POST", body: JSON.stringify(shipstationOrder(order)) });
    const patch = { shipstation_order_id: String(res.orderId), shipstation_synced_at: new Date().toISOString(), shipstation_error: null };
    await patchOrder(env, "id=eq." + order.id, patch);
    return { ok: true, ...patch };
  } catch (e) {
    await patchOrder(env, "id=eq." + order.id, { shipstation_error: String(e.message).slice(0, 500) }).catch(() => {});
    throw e;
  }
}

/* POST /shipstation/push { order_id } — admins only */
async function handleShipstationPush(request, env, cors) {
  const denied = await requireAdmin(request, env);
  if (denied) return json({ error: denied }, 401, cors);
  if (!features(env).shipstation) return json({ error: "ShipStation isn’t set up in the worker." }, 501, cors);
  const body = await readJson(request);
  if (!UUID.test(body.order_id || "")) return json({ error: "Missing order" }, 400, cors);
  const order = await loadOrder(env, "id=eq." + body.order_id);
  if (!order) return json({ error: "Order not found" }, 404, cors);
  // A cancelled order is only sent to cancel its copy in ShipStation.
  if (order.status === "cancelled" && !order.shipstation_order_id) return json({ error: "This order is cancelled and isn’t in ShipStation." }, 409, cors);
  try { return json(await pushToShipstation(env, order), 200, cors); }
  catch (e) { return json({ error: e.message }, 502, cors); }
}

/* POST /shipstation/setup — admins only. Points ShipStation's webhooks at this server (once):
   SHIP_NOTIFY (a label was created) and FULFILLMENT_SHIPPED (an order was marked shipped with a tracking number). */
const SS_EVENTS = ["SHIP_NOTIFY", "FULFILLMENT_SHIPPED"];
async function handleShipstationSetup(request, env, cors) {
  const denied = await requireAdmin(request, env);
  if (denied) return json({ error: denied }, 401, cors);
  if (!features(env).shipstationWebhook) return json({ error: "Add SHIPSTATION_API_KEY, SHIPSTATION_API_SECRET and SHIPSTATION_WEBHOOK_TOKEN to the server secrets first." }, 501, cors);
  // SELF_URL is set when this code runs as a Supabase Edge Function (its public address includes /functions/v1/hw).
  const base = String(env.SELF_URL || new URL(request.url).origin).replace(/\/+$/, "") + "/shipstation/webhook";
  const target = base + "?token=" + encodeURIComponent(env.SHIPSTATION_WEBHOOK_TOKEN);
  const list = await shipstation(env, "webhooks");
  const mine = ((list && list.webhooks) || []).filter((h) => String(h.Url || h.url || "").split("?")[0] === base);
  const added = [];
  for (const h of mine) {
    const ok = (h.Url || h.url) === target && SS_EVENTS.includes(h.HookType || h.hookType);
    if (!ok) await shipstation(env, "webhooks/" + (h.WebHookID || h.webHookId), { method: "DELETE" }).catch(() => {}); // e.g. an old token
  }
  for (const event of SS_EVENTS) {
    if (mine.some((h) => (h.Url || h.url) === target && (h.HookType || h.hookType) === event)) continue;
    const res = await shipstation(env, "webhooks/subscribe", { method: "POST", body: JSON.stringify({ target_url: target, event, store_id: null, friendly_name: "Home Weavers tracking (" + event + ")" }) });
    added.push({ event, id: res && res.id });
  }
  return json({ ok: true, already: added.length === 0, added }, 200, cors);
}

const CARRIERS = { stamps_com: "USPS", usps: "USPS", endicia: "USPS", ups: "UPS", ups_walleted: "UPS", fedex: "FedEx", fedex_walleted: "FedEx", dhl_express: "DHL", dhl_express_worldwide: "DHL", ontrac: "OnTrac" };

/* Saves one ShipStation shipment or fulfillment on our order. `filter` picks the order (by our id or ShipStation's id). */
async function applyShipment(env, filter, s) {
  if (!s || s.voided || !s.trackingNumber) return 0;
  const before = await db(env, "orders?" + filter + "&select=id,status,tracking_number&limit=1");
  const was = Array.isArray(before) && before[0];
  const rows = await patchOrder(env, filter + "&status=in.(new,accepted,packed,shipped)", {
    status: "shipped",
    carrier: CARRIERS[s.carrierCode] || String(s.carrierCode || "").toUpperCase() || null,
    tracking_number: String(s.trackingNumber).slice(0, 100),
    shipped_at: s.shipDate ? new Date(s.shipDate).toISOString() : new Date().toISOString(),
  });
  const updated = Array.isArray(rows) ? rows.length : 0;
  // One "shipped" email per order, and a new one only if the tracking number changes.
  if (updated && was && (was.status !== "shipped" || was.tracking_number !== rows[0].tracking_number)) await sendOrderEmail(env, "shipped", rows[0]);
  return updated;
}

/* Our order for a ShipStation record: labels carry our orderKey; fulfillments only carry ShipStation's orderId. */
function shipmentFilter(s) {
  if (UUID.test(s.orderKey || "")) return "id=eq." + s.orderKey;
  if (/^\d+$/.test(String(s.orderId || ""))) return "shipstation_order_id=eq." + s.orderId;
  return null;
}

/* POST /shipstation/webhook?token=… — ShipStation SHIP_NOTIFY / FULFILLMENT_SHIPPED: { resource_url, resource_type } */
async function handleShipstationWebhook(request, env) {
  if (!features(env).shipstationWebhook) return json({ error: "Not set up" }, 501);
  const token = new URL(request.url).searchParams.get("token") || "";
  if (!safeEqual(token, env.SHIPSTATION_WEBHOOK_TOKEN)) return json({ error: "Forbidden" }, 403);
  const body = await readJson(request);
  if (!SS_EVENTS.includes(body.resource_type)) return json({ ok: true, ignored: body.resource_type || "unknown" });
  let resource;
  try { resource = new URL(String(body.resource_url || "")); } catch { return json({ error: "Bad resource_url" }, 400); }
  // The ShipStation key goes with this request, so only ever call ShipStation itself.
  if (resource.protocol !== "https:" || resource.hostname !== "ssapi.shipstation.com") return json({ error: "Bad resource_url" }, 400);

  let updated = 0, page = 1, pages = 1;
  do {
    resource.searchParams.set("page", String(page));
    const data = await shipstation(env, resource.toString());
    pages = Math.min(Number(data && data.pages) || 1, 20);
    for (const s of [].concat((data && data.shipments) || [], (data && data.fulfillments) || [])) {
      const filter = shipmentFilter(s);
      if (filter) updated += await applyShipment(env, filter, s);
    }
    page++;
  } while (page <= pages);
  return json({ ok: true, updated });
}

/* POST /shipstation/sync { order_id } — admins only. Looks the order up in ShipStation and saves its tracking
   (a safety net if a webhook was missed). */
async function handleShipstationSync(request, env, cors) {
  const denied = await requireAdmin(request, env);
  if (denied) return json({ error: denied }, 401, cors);
  if (!features(env).shipstation) return json({ error: "ShipStation isn’t set up on the server." }, 501, cors);
  const body = await readJson(request);
  if (!UUID.test(body.order_id || "")) return json({ error: "Missing order" }, 400, cors);
  const order = await loadOrder(env, "id=eq." + body.order_id);
  if (!order) return json({ error: "Order not found" }, 404, cors);
  if (!order.shipstation_order_id) return json({ error: "This order isn’t in ShipStation yet." }, 409, cors);
  const num = encodeURIComponent(order.order_number);
  const mine = (s) => !s.voided && s.trackingNumber && (s.orderKey === order.id || String(s.orderId) === String(order.shipstation_order_id));
  const shipments = ((await shipstation(env, "shipments?orderNumber=" + num + "&includeShipmentItems=false")) || {}).shipments || [];
  let found = shipments.filter(mine);
  if (!found.length) found = (((await shipstation(env, "fulfillments?orderNumber=" + num)) || {}).fulfillments || []).filter(mine);
  if (!found.length) return json({ ok: true, shipped: false }, 200, cors);
  const latest = found.sort((a, b) => String(b.shipDate || "").localeCompare(String(a.shipDate || "")))[0];
  const updated = await applyShipment(env, "id=eq." + order.id, latest);
  const fresh = await loadOrder(env, "id=eq." + order.id);
  return json({ ok: true, shipped: true, updated, carrier: fresh && fresh.carrier, tracking_number: fresh && fresh.tracking_number, status: fresh && fresh.status }, 200, cors);
}

/* ================================================================ *
 * Customer emails (Resend). Secrets: RESEND_API_KEY; optional EMAIL_FROM, EMAIL_REPLY_TO.
 * Every email is best-effort: a failed email is logged and never blocks an order change.
 * ================================================================ */
const EMAIL_FROM_DEFAULT = "Home Weavers <orders@homeweavers.net>";

async function storeData(env) {
  const rows = await db(env, "store?id=eq.main&select=data");
  return (rows && rows[0] && rows[0].data) || {};
}

function trackingLink(carrier, number) {
  if (!number) return "";
  const n = encodeURIComponent(number), c = String(carrier || "").toLowerCase();
  if (/usps|stamps/.test(c)) return "https://tools.usps.com/go/TrackConfirmAction?tLabels=" + n;
  if (/ups/.test(c)) return "https://www.ups.com/track?tracknum=" + n;
  if (/fedex/.test(c)) return "https://www.fedex.com/fedextrack/?trknbr=" + n;
  if (/dhl/.test(c)) return "https://www.dhl.com/us-en/home/tracking.html?tracking-id=" + n;
  return "";
}

const money = (n) => "$" + Number(n || 0).toFixed(2);

function emailLayout(brand, site, title, bodyHtml) {
  const b = esc(brand);
  return `<!doctype html><html><body style="margin:0;background:#F7F4EF;font-family:Arial,Helvetica,sans-serif;color:#2A2622">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#F7F4EF;padding:24px 12px"><tr><td align="center">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background:#ffffff;border:1px solid #E6E0D6;border-radius:6px">
<tr><td style="background:#2C463F;padding:18px 24px;border-radius:6px 6px 0 0"><span style="font-family:Georgia,serif;font-size:22px;color:#ffffff">${b}</span></td></tr>
<tr><td style="padding:24px">
<h1 style="font-family:Georgia,serif;font-weight:400;font-size:24px;margin:0 0 14px">${esc(title)}</h1>
${bodyHtml}
</td></tr>
<tr><td style="padding:16px 24px;border-top:1px solid #E6E0D6;font-size:12px;color:#6C6359">
${site ? `<a href="${esc(site)}" style="color:#3A5A52">${esc(site.replace(/^https?:\/\//, "").replace(/\/$/, ""))}</a> · ` : ""}You’re getting this email because you placed an order with ${b}.
</td></tr></table></td></tr></table></body></html>`;
}

function itemsTable(order) {
  const rows = (order.order_items || []).map((i) =>
    `<tr><td style="padding:6px 0;font-size:14px">${esc(i.name)}${i.variant ? ` <span style="color:#6C6359">(${esc(i.variant)})</span>` : ""} × ${Number(i.qty)}</td>` +
    `<td align="right" style="padding:6px 0;font-size:14px">${money(i.line_total)}</td></tr>`).join("");
  const line = (label, value) => `<tr><td style="padding:4px 0;font-size:14px;color:#6C6359">${label}</td><td align="right" style="padding:4px 0;font-size:14px">${value}</td></tr>`;
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="border-top:1px solid #E6E0D6;border-bottom:1px solid #E6E0D6;margin:14px 0">${rows}</table>` +
    `<table role="presentation" width="100%" cellpadding="0" cellspacing="0">` +
    line("Subtotal", money(order.subtotal)) +
    (Number(order.discount) > 0 ? line("Discount" + (order.promo_code ? " (" + esc(order.promo_code) + ")" : ""), "−" + money(order.discount)) : "") +
    line("Shipping", Number(order.shipping) > 0 ? money(order.shipping) : "Free") +
    `<tr><td style="padding:6px 0;font-size:15px"><b>Total</b></td><td align="right" style="padding:6px 0;font-size:15px"><b>${money(order.total)}</b></td></tr></table>`;
}

function button(href, label) {
  return `<p style="margin:18px 0"><a href="${esc(href)}" style="display:inline-block;background:#2C463F;color:#ffffff;text-decoration:none;padding:12px 20px;border-radius:4px;font-size:14px;letter-spacing:.04em">${esc(label)}</a></p>`;
}

/* kind: received | accepted | shipped | cancelled | refunded */
function buildOrderEmail(kind, order, data, extra = {}) {
  const brand = (data.brand && data.brand.name) || "Home Weavers";
  const site = String((data.settings && data.settings.siteUrl) || "").replace(/\/?$/, "/");
  const minutes = Number((data.settings || {}).cancelMinutes);
  const windowMin = minutes >= 0 && minutes <= 1440 ? minutes : 30;
  const trackUrl = site + "page/track-your-order?order=" + encodeURIComponent(order.order_number);
  const first = String(order.name || "").split(" ")[0];
  const hi = `<p style="font-size:15px;line-height:1.6;margin:0 0 10px">Hi ${esc(first || "there")},</p>`;
  const p = (t) => `<p style="font-size:15px;line-height:1.6;margin:0 0 10px">${t}</p>`;
  const num = esc(order.order_number);
  let subject, title, body, text;

  if (kind === "received") {
    subject = `We’ve got your order ${order.order_number}`;
    title = "Thank you for your order";
    body = hi + (order.payment_status === "authorized"
        ? p(`We’ve received order <b>${num}</b>. Your card is approved for <b>${money(order.total)}</b>; you’ll only be charged when we start preparing your order.`)
        : p(`Your payment went through and we’ve received order <b>${num}</b>.`)) +
      (windowMin > 0 ? p(`Changed your mind? You can cancel it yourself for the next <b>${windowMin} minutes</b>` + (order.payment_status === "authorized" ? " and you won’t be charged." : " and get a full refund.") + " After that we start preparing it.") : "") +
      itemsTable(order) + button(trackUrl, windowMin > 0 ? "View or cancel your order" : "View your order");
    text = `Thank you for your order ${order.order_number} (${money(order.total)}).` + (order.payment_status === "authorized" ? " Your card is approved; you'll be charged when we start preparing it." : "") + (windowMin > 0 ? ` You can cancel within ${windowMin} minutes: ${trackUrl}` : ` Track it: ${trackUrl}`);
  } else if (kind === "accepted") {
    subject = `Your order ${order.order_number} is being prepared`;
    title = "We’re preparing your order";
    body = hi + p(`Good news — order <b>${num}</b> is confirmed and we’re getting it ready to ship. We’ll email you the tracking number as soon as it’s on its way.`) +
      button(trackUrl, "Track your order");
    text = `Order ${order.order_number} is confirmed and being prepared. Track it: ${trackUrl}`;
  } else if (kind === "shipped") {
    const link = trackingLink(order.carrier, order.tracking_number);
    subject = `Your order ${order.order_number} has shipped`;
    title = "Your order is on its way";
    body = hi + p(`Order <b>${num}</b> has shipped${order.carrier ? " with <b>" + esc(order.carrier) + "</b>" : ""}.`) +
      p(`Tracking number: <b>${esc(order.tracking_number || "")}</b>`) +
      (link ? button(link, "Track your package") : button(trackUrl, "Track your order"));
    text = `Order ${order.order_number} has shipped${order.carrier ? " with " + order.carrier : ""}. Tracking: ${order.tracking_number || ""} ${link || trackUrl}`;
  } else if (kind === "cancelled") {
    subject = `Order ${order.order_number} is cancelled`;
    title = "Your order is cancelled";
    body = hi + p(`We’ve cancelled order <b>${num}</b> as you asked.`) +
      (extra.voided ? p(`You haven’t been charged. The temporary hold of <b>${money(order.total)}</b> on your card has been released; depending on your bank it disappears within minutes to a few days.`) : "") +
      (extra.refunded ? p(`Your payment of <b>${money(order.total)}</b> has been refunded to your original payment method. It usually shows up in 5–10 business days.`) : "") +
      p(`We hope to see you again soon.`);
    text = `Order ${order.order_number} is cancelled.` + (extra.voided ? " You haven't been charged; the card hold has been released." : "") + (extra.refunded ? ` ${money(order.total)} has been refunded; allow 5–10 business days.` : "");
  } else if (kind === "refunded") {
    subject = `Refund for order ${order.order_number}`;
    title = "Your refund is on its way";
    body = hi + p(`We’ve refunded ${extra.amount != null ? "<b>" + money(extra.amount) + "</b>" : "your payment"} for order <b>${num}</b> to your original payment method. It usually shows up in 5–10 business days.`);
    text = `We've refunded ${extra.amount != null ? money(extra.amount) : "your payment"} for order ${order.order_number}. Allow 5–10 business days.`;
  } else {
    return null;
  }
  return { subject, html: emailLayout(brand, site, title, body), text };
}

async function sendOrderEmail(env, kind, order, extra) {
  if (!env.RESEND_API_KEY || !order || !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(order.email || "")) return false;
  try {
    const data = await storeData(env);
    const msg = buildOrderEmail(kind, order, data, extra);
    if (!msg) return false;
    const replyTo = env.EMAIL_REPLY_TO || (data.contact && data.contact.email) || undefined;
    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { Authorization: "Bearer " + env.RESEND_API_KEY, "Content-Type": "application/json", "Idempotency-Key": kind + "-" + order.id },
      body: JSON.stringify({ from: env.EMAIL_FROM || EMAIL_FROM_DEFAULT, to: [order.email], reply_to: replyTo, subject: msg.subject, html: msg.html, text: msg.text }),
    });
    if (!res.ok) console.error("email " + kind + " " + order.order_number + " failed", res.status, (await res.text()).slice(0, 200));
    return res.ok;
  } catch (e) {
    console.error("email " + kind + " failed", e && e.message);
    return false;
  }
}

/* POST /email/test { kind } — admins only. Sends a sample order email to the signed-in admin's own address. */
async function handleEmailTest(request, env, cors) {
  const denied = await requireAdmin(request, env);
  if (denied) return json({ error: denied }, 401, cors);
  if (!env.RESEND_API_KEY) return json({ error: "Add the secret RESEND_API_KEY first." }, 501, cors);
  const who = await fetch(env.SUPABASE_URL + "/auth/v1/user", { headers: { apikey: env.SUPABASE_PUBLISHABLE_KEY, Authorization: request.headers.get("Authorization") } }).then((r) => r.json()).catch(() => ({}));
  if (!who || !who.email) return json({ error: "Couldn’t read your admin email." }, 400, cors);
  const body = await readJson(request);
  const kind = ["received", "accepted", "shipped", "cancelled", "refunded"].includes(body.kind) ? body.kind : "received";
  const sample = {
    id: "test-" + Date.now(), order_number: "HW-TEST", email: who.email, name: "Test Customer",
    subtotal: 64, discount: 0, shipping: 9.95, total: 73.95, carrier: "USPS", tracking_number: "9400100000000000000000",
    order_items: [{ name: "Sample item (this is a test email)", variant: "Blue", qty: 1, line_total: 64 }],
  };
  const sent = await sendOrderEmail(env, kind, sample, { refunded: true, amount: 73.95 });
  return sent ? json({ ok: true, to: who.email, kind }, 200, cors) : json({ error: "Resend didn’t accept the email. Check that homeweavers.net is verified and the key has sending access." }, 502, cors);
}

/* ---------------------------------------------------------------- *
 * Customer accounts — sign in with a code sent by email. No passwords are stored anywhere.
 *   POST /account/code   { email }        → emails a 6-digit code, but only if that email has placed an order.
 *                                           The answer is the same either way, so nobody can test who shops here.
 *   POST /account/verify { email, code }  → { token } — a signed 30-day session
 *   POST /account/orders  Authorization: Bearer <token> → that customer's orders + last address (for checkout)
 * Codes are kept only as keyed hashes in customer_login_codes (service role only) and deleted after a day.
 * ---------------------------------------------------------------- */
const EMAIL_RE = /^[^@\s]+@[^@\s]+\.[^@\s]+$/;
const CODE_MINUTES = 10, CODE_TRIES = 5, SESSION_DAYS = 30;
const CODES_PER_EMAIL_HOUR = 5, CODES_PER_IP_HOUR = 20;
const PAID_STATES = "(authorized,paid,refunded,voided,failed)";

const enc = new TextEncoder();
const b64url = (bytes) => btoa(String.fromCharCode(...new Uint8Array(bytes))).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
const hexOf = (bytes) => [...new Uint8Array(bytes)].map((b) => b.toString(16).padStart(2, "0")).join("");
async function hmacBytes(key, msg) {
  const k = await crypto.subtle.importKey("raw", enc.encode(key), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]);
  return crypto.subtle.sign("HMAC", k, enc.encode(msg));
}
/* Session/code key: CUSTOMER_SESSION_SECRET if set, otherwise derived from the service key (never leaves the server). */
async function accountKey(env) {
  return env.CUSTOMER_SESSION_SECRET || hexOf(await hmacBytes(String(env.SUPABASE_SERVICE_ROLE_KEY || ""), "hw-customer-session-v1"));
}
function clientIp(request) {
  return String(request.headers.get("cf-connecting-ip") || request.headers.get("x-forwarded-for") || "").split(",")[0].trim();
}
async function countRows(env, path) {
  const rows = await db(env, path + "&select=id&limit=100");
  return Array.isArray(rows) ? rows.length : 0;
}

async function handleAccountCode(request, env, cors) {
  if (!features(env).database || !env.RESEND_API_KEY) return json({ error: "Sign-in isn’t available right now. You can still track an order with its number and email." }, 501, cors);
  const body = await readJson(request);
  const email = String(body.email || "").trim().toLowerCase();
  if (!EMAIL_RE.test(email) || email.length > 254) return json({ error: "Enter a valid email address." }, 400, cors);
  const key = await accountKey(env);
  const ipHash = hexOf(await hmacBytes(key, "ip:" + clientIp(request))).slice(0, 32);
  const hourAgo = encodeURIComponent(new Date(Date.now() - 3600000).toISOString());

  await db(env, "customer_login_codes?created_at=lt." + encodeURIComponent(new Date(Date.now() - 86400000).toISOString()), { method: "DELETE" }).catch(() => {});
  if (await countRows(env, "customer_login_codes?ip_hash=eq." + ipHash + "&created_at=gt." + hourAgo) >= CODES_PER_IP_HOUR ||
      await countRows(env, "customer_login_codes?email=eq." + encodeURIComponent(email) + "&created_at=gt." + hourAgo) >= CODES_PER_EMAIL_HOUR) {
    return json({ error: "Too many codes asked for. Please try again in an hour." }, 429, cors);
  }
  const sameAnswer = json({ ok: true }, 200, cors);
  const known = await db(env, "orders?email=eq." + encodeURIComponent(email) + "&payment_status=in." + PAID_STATES + "&select=id&limit=1");
  const isCustomer = Array.isArray(known) && known.length > 0;
  // Unknown emails are counted too (with a hash nothing can match), so the limits can't be used to test addresses either.
  const code = String(crypto.getRandomValues(new Uint32Array(1))[0] % 1000000).padStart(6, "0");
  const rows = await db(env, "customer_login_codes", {
    method: "POST", headers: { Prefer: "return=representation" },
    body: JSON.stringify({
      email, ip_hash: ipHash,
      code_hash: isCustomer ? hexOf(await hmacBytes(key, "code:" + email + ":" + code)) : "none",
      expires_at: new Date(Date.now() + CODE_MINUTES * 60000).toISOString(),
    }),
  });
  if (!isCustomer) return sameAnswer;
  const data = await storeData(env);
  const brand = (data.brand && data.brand.name) || "Home Weavers";
  const site = String((data.settings && data.settings.siteUrl) || "").replace(/\/?$/, "/");
  const html = emailLayout(brand, site, "Your sign-in code",
    `<p style="font-size:15px;line-height:1.6;margin:0 0 10px">Use this code to sign in and see your orders:</p>` +
    `<p style="font-size:32px;letter-spacing:.3em;font-weight:bold;margin:16px 0;font-family:Georgia,serif">${code}</p>` +
    `<p style="font-size:14px;line-height:1.6;color:#6C6359;margin:0">It works for ${CODE_MINUTES} minutes. If you didn’t ask for it, you can ignore this email — nobody can sign in without the code.</p>`);
  const res = await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: { Authorization: "Bearer " + env.RESEND_API_KEY, "Content-Type": "application/json", "Idempotency-Key": "login-" + ((rows && rows[0] && rows[0].id) || Date.now()) },
    body: JSON.stringify({ from: env.EMAIL_FROM || EMAIL_FROM_DEFAULT, to: [email], subject: `${code} is your ${brand} sign-in code`, html, text: `Your ${brand} sign-in code is ${code}. It works for ${CODE_MINUTES} minutes. If you didn't ask for it, ignore this email.` }),
  });
  if (!res.ok) console.error("login email failed", res.status, (await res.text()).slice(0, 200));
  return sameAnswer;
}

async function handleAccountVerify(request, env, cors) {
  if (!features(env).database) return json({ error: "Sign-in isn’t available right now." }, 501, cors);
  const body = await readJson(request);
  const email = String(body.email || "").trim().toLowerCase();
  const code = String(body.code || "").replace(/\s+/g, "");
  const wrong = (extra) => json(Object.assign({ error: "That code isn’t right or has expired. Check it, or ask for a new one." }, extra || {}), 400, cors);
  if (!EMAIL_RE.test(email) || !/^\d{6}$/.test(code)) return wrong();
  const now = new Date().toISOString();
  const rows = await db(env, "customer_login_codes?email=eq." + encodeURIComponent(email) + "&used_at=is.null&expires_at=gt." + encodeURIComponent(now) + "&select=id,code_hash,attempts&order=created_at.desc&limit=1");
  const row = Array.isArray(rows) && rows[0];
  if (!row) return wrong();
  if (row.attempts >= CODE_TRIES) return json({ error: "Too many tries. Ask for a new code." }, 429, cors);
  // Count the try first (only if nobody else counted it meanwhile), then compare.
  const bumped = await db(env, "customer_login_codes?id=eq." + row.id + "&attempts=eq." + row.attempts, { method: "PATCH", headers: { Prefer: "return=representation" }, body: JSON.stringify({ attempts: row.attempts + 1 }) });
  if (!Array.isArray(bumped) || !bumped.length) return wrong();
  const key = await accountKey(env);
  if (!safeEqual(row.code_hash, hexOf(await hmacBytes(key, "code:" + email + ":" + code)))) return wrong({ triesLeft: Math.max(0, CODE_TRIES - row.attempts - 1) });
  const used = await db(env, "customer_login_codes?id=eq." + row.id + "&used_at=is.null", { method: "PATCH", headers: { Prefer: "return=representation" }, body: JSON.stringify({ used_at: now }) });
  if (!Array.isArray(used) || !used.length) return wrong();
  const exp = Math.floor(Date.now() / 1000) + SESSION_DAYS * 86400;
  const payload = b64url(enc.encode(JSON.stringify({ e: email, x: exp, n: b64url(crypto.getRandomValues(new Uint8Array(9))) })));
  const token = payload + "." + b64url(await hmacBytes(key, "session:" + payload));
  return json({ ok: true, token, email, expires: new Date(exp * 1000).toISOString() }, 200, cors);
}

/* The email of a valid customer session, or null. */
async function customerEmail(request, env) {
  const m = /^Bearer\s+([A-Za-z0-9_-]+)\.([A-Za-z0-9_-]+)$/.exec(request.headers.get("Authorization") || "");
  if (!m) return null;
  const expect = b64url(await hmacBytes(await accountKey(env), "session:" + m[1]));
  if (!safeEqual(expect, m[2])) return null;
  try {
    const p = JSON.parse(atob(m[1].replace(/-/g, "+").replace(/_/g, "/")));
    return p && EMAIL_RE.test(p.e || "") && Number(p.x) * 1000 > Date.now() ? p.e : null;
  } catch { return null; }
}

async function handleAccountOrders(request, env, cors) {
  if (!features(env).database) return json({ error: "Sign-in isn’t available right now." }, 501, cors);
  const email = await customerEmail(request, env);
  if (!email) return json({ error: "Please sign in again.", signedOut: true }, 401, cors);
  // Only what the customer needs to see: no internal ids, notes, payment references or tokens.
  const cols = "order_number,created_at,paid_at,status,payment_status,subtotal,discount,shipping,tax,total,promo_code,carrier,tracking_number,shipped_at,cancel_requested_at,name,phone,shipping_address,order_items(name,variant,qty,image,line_total)";
  const rows = await db(env, "orders?email=eq." + encodeURIComponent(email) + "&payment_status=in." + PAID_STATES + "&select=" + cols + "&order=created_at.desc&limit=50");
  const list = Array.isArray(rows) ? rows : [];
  const last = list[0];
  const profile = last ? { name: last.name || "", phone: last.phone || "", address: last.shipping_address || {} } : null;
  const orders = list.map((o) => {
    const c = Object.assign({}, o, { items: o.order_items || [] });
    delete c.order_items; delete c.name; delete c.phone; delete c.shipping_address;
    return c;
  });
  return json({ ok: true, email, orders, profile }, 200, cors);
}


/* ---- Supabase Edge Function wrapper ---- */
const env = new Proxy({}, {
  get(_, key) {
    const k = String(key);
    const v = Deno.env.get(k);
    if (v !== undefined && v !== '') return v;
    if (k === 'SUPABASE_PUBLISHABLE_KEY') return Deno.env.get('SUPABASE_ANON_KEY');
    // Supabase doesn't allow secret names starting with SUPABASE_, so a manually added key uses this name.
    if (k === 'SUPABASE_SERVICE_ROLE_KEY') return Deno.env.get('SERVICE_ROLE_KEY');
    if (k === 'SELF_URL') return (Deno.env.get('SUPABASE_URL') || '').replace(/\/+$/, '') + '/functions/v1/hw';
    return undefined;
  },
});

Deno.serve((req) => {
  // The function sees its path as /hw/... (or /functions/v1/hw/...); the handler expects /... .
  const url = new URL(req.url);
  url.pathname = url.pathname.replace(/^\/(?:functions\/v1\/)?hw(?=\/|$)/, '') || '/';
  return handler.fetch(new Request(url.toString(), req), env);
});
