#!/usr/bin/env node
/* Builds the Supabase Edge Function supabase/functions/hw/index.ts from ai-proxy.worker.js,
   so the same tested code runs on Supabase (Deno) or on a Cloudflare Worker.
   Run after changing ai-proxy.worker.js:  node tools/build-edge.js
   Then paste supabase/functions/hw/index.ts into Supabase → Edge Functions → hw → Code → Deploy. */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
let src = fs.readFileSync(path.join(ROOT, 'ai-proxy.worker.js'), 'utf8');
if (src.split('export default {').length !== 2) throw new Error('ai-proxy.worker.js: expected one "export default {"');
src = src.replace('export default {', 'const handler = {');

const out = `// @ts-nocheck
/* Home Weavers — Supabase Edge Function "hw". GENERATED by tools/build-edge.js from ai-proxy.worker.js; edit that file instead.
   Address: https://<project>.supabase.co/functions/v1/hw   (turn OFF "Verify JWT" for this function:
   Stripe and ShipStation webhooks can't send a Supabase login; admin routes check the admin session themselves.)
   Secrets: Supabase → Edge Functions → Secrets. SUPABASE_URL, SUPABASE_ANON_KEY and SUPABASE_SERVICE_ROLE_KEY are provided by Supabase. */

${src}

/* ---- Supabase Edge Function wrapper ---- */
const env = new Proxy({}, {
  get(_, key) {
    const k = String(key);
    const v = Deno.env.get(k);
    if (v !== undefined && v !== '') return v;
    if (k === 'SUPABASE_PUBLISHABLE_KEY') return Deno.env.get('SUPABASE_ANON_KEY');
    // Supabase doesn't allow secret names starting with SUPABASE_, so a manually added key uses this name.
    if (k === 'SUPABASE_SERVICE_ROLE_KEY') return Deno.env.get('SERVICE_ROLE_KEY');
    if (k === 'SELF_URL') return (Deno.env.get('SUPABASE_URL') || '').replace(/\\/+$/, '') + '/functions/v1/hw';
    return undefined;
  },
});

Deno.serve((req) => {
  // The function sees its path as /hw/... (or /functions/v1/hw/...); the handler expects /... .
  const url = new URL(req.url);
  url.pathname = url.pathname.replace(/^\\/(?:functions\\/v1\\/)?hw(?=\\/|$)/, '') || '/';
  return handler.fetch(new Request(url.toString(), req), env);
});
`;

const file = path.join(ROOT, 'supabase', 'functions', 'hw', 'index.ts');
fs.mkdirSync(path.dirname(file), { recursive: true });
fs.writeFileSync(file, out);
console.log('Wrote supabase/functions/hw/index.ts (' + Math.round(out.length / 1024) + ' KB).');
